// <auto-generated />
namespace CS322_PZ01.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class narucivanje : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(narucivanje));
        
        string IMigrationMetadata.Id
        {
            get { return "201712021742144_narucivanje"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
